### ISSUE TITLE
The link to Keith Anderson's blog does not work

### ISSUE THREAD

**Issue by soocodes** [Isilon/isilon_data_insights_connector#101]
The link below (which is a part of Readme) does't land on required result 
https://community.emc.com/blogs/keith/2017/01/26/isilon-data-insights-connector--do-it-yourself-isilon-monitoring

**Comment by tenortim** [comment]
A colleague of mine had saved a copy of Keith's blog post in OneNote.
I have attempted to resurrect it as a Wiki page on this site.
Please check the Wiki tab.
