### ISSUE TITLE
Need support for Isilon SDK 8.2 for OneFS 8.2.2.x clusters

### ISSUE THREAD

**Issue by xniega-be** [Isilon/isilon_data_insights_connector#103]
Majority of Isilon clusters running 8.1.2 and below are working with Isilon SDK 8.0, but after the upgrade of one cluster to OneFS 8.2.2.0, metric collection stopped working.

**Comment by tenortim** [comment]
The 8.0 SDK has no issues retrieving statistics from 8.2.2 clusters (it is monitoring multiple internal 8.2.2 clusters).
I believe this is a duplicate of issue #66 
Could you please remove the `node.memory.cache` from your data insights config file and retry?

**Comment by xniega-be** [comment]
This was exactly the fix. Thank you!
