### ISSUE TITLE
Value calcualtion different in dashboards

### ISSUE THREAD

**Issue by eschek87** [Isilon/isilon_data_insights_connector#12]
Hi guys,

great work! Nice monitoring! But i have found some differences between the dashboards "cluster summary" and "cluster detail" for nfs3 and smb2 (throughput, op/s, latency). One example:
cluster summary nfsv3 op/s: metric calculation with "mean"
-> SELECT mean("op_count") FROM "cluster.protostats.nfs.total" WHERE "cluster" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)

cluster detail nfsv3 op/s: metric calculation with "max"
-> SELECT max("op_count") FROM "cluster.protostats.nfs.total" WHERE "cluster" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)

cluster summary nfsv3 throughput: metric calculation with "mean"
-> SELECT mean("in_rate") +mean("out_rate") FROM "cluster.protostats.nfs.total" WHERE "cluster" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)

cluster detail nfsv3 throughput: metric calculation with "max" and "mean"
-> SELECT max("in_rate") + mean("out_rate") FROM "cluster.protostats.nfs.total" WHERE "cluster" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)

The same affects smb stats....maybe you can check this?

**Comment by tenortim** [comment]
Fix is in commit ed87ee65d6ece4875278a7c075713319d521804d on branch dashboard_updates. It just needs to be merged to master.
