### ISSUE TITLE
Complex Password Index Bug

### ISSUE THREAD

**Issue by Soldrym** [Isilon/isilon_data_insights_connector#141]
### Issue
Adding a new cluster with a complex password (@) fails. This is post 9c82c4e commit.
> python[26625]: Traceback (most recent call last):
> python[26625]: File "/opt/isilon_data_insights_connector/isi_data_insights_d.py", line 78, in <module>
> python[26625]: main()
> python[26625]: File "/opt/isilon_data_insights_connector/isi_data_insights_d.py", line 55, in main
> python[26625]: configure_via_file(daemon, args, config_file)
> python[26625]: File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 711, in configure_via_file
> python[26625]: config_file.get(MAIN_CFG_SEC, "clusters")
> python[26625]: File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 111, in _process_config_file_clusters
> python[26625]: verify_ssl_split = at_split[-1].split(":", 1)
> python[26625]: AttributeError: 'list' object has no attribute 'split'

### Problem
Line 88 of isi_data_insights_config.py creates the "rightside" variable out of at_split[-1:]. This results in a list, which then blows up on line 111.

### Resolution
Remove the colon from line 88, as you only need the last index of at_split for the right side.

**Comment by tenortim** [comment]
I think this could be greatly simplified by me simply calling rsplit rather than split. I'm going to experiment.
