### ISSUE TITLE
can't connect to cluster configured in isi_data_insights_d.cfg

### ISSUE THREAD

**Issue by Romano23** [Isilon/isilon_data_insights_connector#142]
`isi_data_insights_d.cfg cluster configuration
# clusters in this section are queried for all stat groups
# clusters: [username1:password1@]<ip-or-host-address1>[:True|False]
#       [[username2:password2]@<ip-or-host-address2>[:True|False]]
#       [[username3:password3]@<ip-or-host-address3>[:True|False]]
#       ...
# If you don't specify the username and password then you will be prompted
# for them when the daemon starts up.
# Use the optional True or False on the end to specify whether the cluster's
# SSL certificate should be verified. If it is omitted then the default is
# False (i.e. don't verify SSL cert).
clusters:
#example with fake IP 
        grafana:grafana@10.10.10.10   

The output when I start the connector
`
admin@centos7template isilon_data_insights_connector-master]$ ./isi_data_insights_d.py start
2022-11-04 07:21:53,286 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcea413a128>: Failed to establish a new connection: [Errno 110] Connection timed out',)': /session/1/session

**Comment by tenortim** [comment]
Hi @Romano23,
did you find out what was wrong. From the error messages you were getting, it sounded like you were connecting to an IP address that wasn't reachable from where the client was running.
