### ISSUE TITLE
Unable to load the stats processor : influxdb_plugin

### ISSUE THREAD

**Issue by David-EBIND** [Isilon/isilon_data_insights_connector#144]
I'm getting this error after following the steps mentioned. 

Influxdb installed is 1.8.10 and the port listening is 8086

Grafana installed is 9.2.4. I have modified the isi_data_insights_d.cfg file with the influxdb auth and have entered my cluster IP as well. But still I'm getting this error and I'm stuck at this step.

**Comment by David-EBIND** [comment]
For your information, I'm testing to monitor only one cluster which is in 9.2.1.8 Version.

**Comment by tenortim** [comment]
Hi @David-EBIND,
that error means that the code was unable to import the influxdb_plugin.py module.
There are several reasons that that could happen:

- Check that influxdb_plugin.py is in the directory where you're running the collector and that it's readable and correct
- Did you install of the requirements, are you using a virtualenv, and, if you are, are you activating it before trying to start the collector?
You can check the latter before trying to start the collector by running python, and then typing `import influxdb` and verifying that it succeeds.

**Comment by David-EBIND** [comment]
Hi @tenortim, 

I sorted out that stats processor loading error, but now I need to have the SDK version for 9.2.1.8 ? I couldn't able to find the sdk for this specific version. We have it only for the 9_0_0 and 9_1_0. 

I would like to know whether 9_0_0 will work for the 9.2.1.8 version ? If yes, what changes i have to make on the sdk utils python file.

**Comment by tenortim** [comment]
Hi @David-EBIND,
The API is versioned and SDK gets built for each version. The stats API endpoint we use hasn't changed since OneFS 8.0 (stats endpoint version 3). So any version will do.
The code still has support for 7.2 though that should probably be dropped at this point.

**Comment by psbl-it** [comment]
> Hi @tenortim,
> 
> I sorted out that stats processor loading error, but now I need to have the SDK version for 9.2.1.8 ? I couldn't able to find the sdk for this specific version. We have it only for the 9_0_0 and 9_1_0.
> 
> I would like to know whether 9_0_0 will work for the 9.2.1.8 version ? If yes, what changes i have to make on the sdk utils python file.

Hey @David-EBIND 
How were you able to resolve the initial issue? I can't seem to figure it out.

**Comment by David-EBIND** [comment]
Yes this is working fine, I wonder whether this will work on 9.4.X version ?

**Comment by tenortim** [comment]
> Yes this is working fine, I wonder whether this will work on 9.4.X version ?

Yes, it will/does.
The API design uses a versioned model where each subsequent OneFS release bumps the version, and any new endpoints, or endpoints where functionality is changed or extended receive a new (additional) version endpoint, **but** all of the previous versions are still available and don't change. We guarantee this behavior so that you don't need to change code that leverages the API when a new OneFS release ships. Unless you need to take advantage of the new functionality, you can continue to use the same (older) endpoint version on newer releases of the OS.
