### ISSUE TITLE
isi_data_insights/autogen New files not created / updated

### ISSUE THREAD

**Issue by bowdreyn** [Isilon/isilon_data_insights_connector#15]
We successfully installed the isi_data_insights connector and started receiving stats fcrom all of our Isilon clusters. This only worked for a day or two. We do not have any new directories or files in the isi_data_insights/autogen directory since the first days we started it up. 

We have checked configuration, looks ok. When we attempt to restart the daemon "isi_data_insight_d.py restart" we find the following lines in the log:

2017-01-13 12:31:50,147:daemons.startstop.simple:INFO: Succesfully stopped the process.
2017-01-13 12:31:50,148:daemons.startstop.simple:ERROR: The process is already running with pid 1550.

We are not sure what should be in the .pid file and how it is populated. 

Any help in getting the isilons to update the connector would be greatly appreciated.

**Comment by apecoraro** [comment]
There is a bug with the connector where it can think that it is still running when it is not actually running. We actually have a fix here:  https://github.com/Isilon/isilon_data_insights_connector/pull/14

Or you can just upgrade your daemons package to version 2.3.0 using pip. Then try running it again.

Or a quick fix is to just delete the file: isi_data_insights_d.pid, which, if you used the default settings, will be in the same directory as the config file and other Python code files.

**Comment by apecoraro** [comment]
Sorry I got the version number of the fixed daemons package incorrect. It is 1.3.0 not 2.3.0.

**Comment by bowdreyn** [comment]
Hi there, we've upgraded the deamons package and we had to populate the isi_data_insights_d.pid file withthe current deamon pid. The collector is now working as expected. many thanks for your help in sorting this out. Much appreciated.
