### ISSUE TITLE
NFSv3 Op/s on summary versus detail dashboard

### ISSUE THREAD

**Issue by keithxanderson** [Isilon/isilon_data_insights_connector#21]
“Isilon Data Insights Cluster Summary” NFSv3 Op/s singlestat/widget uses SELECT FROM cluster.protostats.nfs.total and uses field (op_count) mean()
 
If you click the NFSv3 Op/s widget it takes you to the “Isilon Data Insights Cluster Detail” dashboard.  The same NFSv3 Op/s widget now uses field(op_rate) -> SELECT mean("op_rate") FROM "cluster.protostats.nfs.total" WHERE "cluster" =~ /^$cluster$/ AND $timeFilter GROUP BY time($interval) fill(null)
 
Request is to keep these consistent and use op_rate for both.

**Comment by apecoraro** [comment]
This is now fixed:

https://github.com/Isilon/isilon_data_insights_connector/commit/5603270954d9747e210daa8cddd7d123b712e995
