### ISSUE TITLE
syntax error on centos 6.7/python 2.6.6/OneFS 8.0.1

### ISSUE THREAD

**Issue by nickyruggs** [Isilon/isilon_data_insights_connector#24]
Here is a fresh install i did today can't tell if its python, SDK or OS issue...  can you please double check

knic@tomservo:~$ ssh root@nr-hdp-zoo2
root@nr-hdp-zoo2's password: 
Last login: Tue Mar 14 10:39:46 2017 from 10.97.53.63
[root@nr-hdp-zoo2 ~]# cd /opt
[root@nr-hdp-zoo2 opt]# cd isilon_data_insights_connector-master/
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# ls
example_isi_data_insights_d.cfg                      isi_data_insights_d.py
grafana_cluster_capacity_utilization_dashboard.json  IsilonDataInsightsClusterCapacityUtilizationTable.JPG
grafana_cluster_detail_dashboard.json                IsilonDataInsightsClusterDetail.JPG
grafana_cluster_list_dashboard.json                  IsilonDataInsightsClusterProtocolDetail.JPG
grafana_cluster_protocol_dashboard.json              IsilonDataInsightsMultiClusterSummary.JPG
hadoop_isi_data_insights_d.cfg                       isi_sdk_utils.py
influxdb_plugin.py                                   isi_sdk_utils.pyc
isi_api_client_7_2.py                                isi_stats_client.py
isi_api_client_8_0.py                                isi_stats_client.pyc
isi_api_client.py                                    LICENSE
isi_data_insights_config.py                          README_KAPACITOR_INTEGRATION.md
isi_data_insights_config.pyc                         README.md
isi_data_insights_daemon.py                          requirements.txt
isi_data_insights_daemon.pyc                         setup_venv.sh
isi_data_insights_d.cfg
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# which python
/usr/bin/python
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# python -V
Python 2.6.6
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# uname -a
Linux nr-hdp-zoo2 2.6.32-642.15.1.el6.x86_64 #1 SMP Fri Feb 24 14:31:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# pwd
/opt/isilon_data_insights_connector-master
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# more isi_data_insights_d.cfg
[isi_data_insights_d]
# Parameters specified on the command line will supersede the parameters
# in this section.
# pid_file: /var/run/isi_data_insights_d.pid
# log_file: /var/run/isi_data_insights_d.log
# default log_level is INFO
# log_level: DEBUG
stats_processor: influxdb_plugin
# Use "auth" as the 4th arg in order to be prompted for the
# InfluxDB username and password stats_processor_args, example:
# localhost 8086 isi_data_insights auth
stats_processor_args: localhost 8086 isi_data_insights

# clusters in this section are queried for all stat groups
# clusters: [username1:password1@]<ip-or-host-address1>[:True|False]
#       [[username2:password2]@<ip-or-host-address2>[:True|False]]
#       [[username3:password3]@<ip-or-host-address3>[:True|False]]
#       ...
# If you don't specify the username and password then you will be prompted
# for them when the daemon starts up.
# Use the optional True or False on the end to specify whether the cluster's
# SSL certificate should be verified. If it is omitted then the default is
# False (i.e. don't verify SSL cert).
clusters:  root:emc@10.111.158.70:False

# Specifies the active list of stat groups to query, each stat group name
# specified here should have a corresponding section in the config file.
active_stat_groups: cluster_cpu_stats
    cluster_network_traffic_stats
    cluster_client_activity_stats
    cluster_health_stats
    ifs_space_stats
    ifs_rate_stats
    node_load_stats
    cluster_disk_rate_stats
    cluster_proto_stats
    cache_stats
    heat_total_stats

# The min_update_interval_override param provides ability to override the
# minimum interval that the daemon will query for a set of stats. The purpose
# of the minimum interval, which defaults to 30 seconds, is to prevent
# the daemon's queries from putting too much stress on the cluster.
# The default value is 30 seconds.
# min_update_interval_override = 15

[cluster_cpu_stats]
# The clusters (optional) param defines a list of clusters specific to this
# group.
# clusters: 10.25.69.74 10.25.69.75
# update interval is in seconds or use *<number> to base the update interval
# off each stat's collection interval (i.e. *2 == 2 times the collection
# interval, *1 == * == 1 times the collection invterval of each stat)
update_interval: *
stats: cluster.cpu.sys.avg
    cluster.cpu.user.avg
    cluster.cpu.idle.avg
    cluster.cpu.intr.avg

[cluster_network_traffic_stats]
update_interval: *
stats: cluster.net.ext.bytes.in.rate
    cluster.net.ext.bytes.out.rate
    cluster.net.ext.packets.in.rate
    cluster.net.ext.packets.out.rate
    cluster.net.ext.errors.in.rate
    cluster.net.ext.errors.out.rate

[cluster_client_activity_stats]
update_interval: *
stats: node.clientstats.active.ftp
    node.clientstats.active.hdfs
    node.clientstats.active.http
    node.clientstats.active.lsass_out
    node.clientstats.active.jobd
    node.clientstats.active.nfs3
    node.clientstats.active.nfs4
    node.clientstats.active.nlm
    node.clientstats.active.papi
    node.clientstats.active.siq
    node.clientstats.active.cifs
    node.clientstats.active.smb1
    node.clientstats.active.smb2
    node.clientstats.connected.ftp
    node.clientstats.connected.hdfs
    node.clientstats.connected.http
    node.clientstats.connected.nfs
    node.clientstats.connected.nlm
    node.clientstats.connected.papi
    node.clientstats.connected.siq
    node.clientstats.connected.cifs

[cluster_health_stats]
update_interval: *
stats: cluster.health
  cluster.node.count.all
  cluster.node.count.down
 
[ifs_space_stats]
update_interval: *
stats: ifs.bytes.avail
  ifs.bytes.free
  ifs.bytes.used
  ifs.bytes.total
  ifs.percent.free
  ifs.percent.avail
  ifs.percent.used

[ifs_rate_stats]
update_interval: *
stats: ifs.bytes.in.rate
  ifs.bytes.out.rate
  ifs.ops.in.rate
  ifs.ops.out.rate
 
[node_load_stats]
update_interval: *
stats: node.cpu.throttling
  node.load.1min
  node.load.5min
  node.load.15min
  node.memory.used
  node.memory.free
  node.memory.cache
  node.open.files
 
[cluster_disk_rate_stats]
update_interval: *
stats: cluster.disk.xfers.rate
  cluster.disk.xfers.in.rate
  cluster.disk.xfers.out.rate
  cluster.disk.bytes.in.rate
  cluster.disk.bytes.out.rate

[cluster_proto_stats]
update_interval: *
stats: cluster.protostats.nfs
  cluster.protostats.nlm
  cluster.protostats.cifs
  cluster.protostats.ftp
  cluster.protostats.http
  cluster.protostats.siq
  cluster.protostats.jobd
  cluster.protostats.smb2
  cluster.protostats.nfs4
  cluster.protostats.irp
  cluster.protostats.lsass_in
  cluster.protostats.lsass_out
  cluster.protostats.papi
  cluster.protostats.hdfs
  cluster.protostats.nfs.total
  cluster.protostats.nlm.total
  cluster.protostats.cifs.total
  cluster.protostats.ftp.total
  cluster.protostats.http.total
  cluster.protostats.siq.total
  cluster.protostats.jobd.total
  cluster.protostats.smb2.total
  cluster.protostats.nfs4.total
  cluster.protostats.irp.total
  cluster.protostats.lsass_in.total
  cluster.protostats.lsass_out.total
  cluster.protostats.papi.total
  cluster.protostats.hdfs.total

[cache_stats]
update_interval: *
stats: node.ifs.cache

[heat_total_stats]
update_interval: *
stats: node.ifs.heat.lock.total
  node.ifs.heat.blocked.total
  node.ifs.heat.contended.total
  node.ifs.heat.deadlocked.total
  node.ifs.heat.write.total
  node.ifs.heat.read.total
  node.ifs.heat.lookup.total
  node.ifs.heat.rename.total
  node.ifs.heat.link.total
  node.ifs.heat.unlink.total
  node.ifs.heat.getattr.total
  node.ifs.heat.setattr.total
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# 
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# sudo pip install -r requirements.txt
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Requirement already satisfied: daemons>=1.3.0 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: influxdb>=2.12.0 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: pip>=8.0.2 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: urllib3>=1.13.1 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: isi_sdk_8_0>=0.1.2 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: isi_sdk_7_2>=0.1.2 in /usr/lib/python2.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: requests>=1.0.3 in /usr/lib/python2.6/site-packages (from influxdb>=2.12.0->-r requirements.txt (line 2))
Requirement already satisfied: six>=1.9.0 in /usr/lib/python2.6/site-packages (from influxdb>=2.12.0->-r requirements.txt (line 2))
Requirement already satisfied: pytz in /usr/lib/python2.6/site-packages (from influxdb>=2.12.0->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil>=2.0.0 in /usr/lib/python2.6/site-packages (from influxdb>=2.12.0->-r requirements.txt (line 2))
Requirement already satisfied: certifi in /usr/lib/python2.6/site-packages (from isi_sdk_8_0>=0.1.2->-r requirements.txt (line 5))
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]# ./isi_data_insights_d.py start
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 4, in <module>
    from isi_data_insights_config import parse_cli, \
  File "/opt/isilon_data_insights_connector-master/isi_data_insights_config.py", line 15, in <module>
    import isi_sdk_utils
  File "/opt/isilon_data_insights_connector-master/isi_sdk_utils.py", line 6, in <module>
    import isi_sdk_8_0
  File "/usr/lib/python2.6/site-packages/isi_sdk_8_0/__init__.py", line 764, in <module>
    from .apis.antivirus_api import AntivirusApi
  File "/usr/lib/python2.6/site-packages/isi_sdk_8_0/apis/__init__.py", line 4, in <module>
    from .antivirus_api import AntivirusApi
  File "/usr/lib/python2.6/site-packages/isi_sdk_8_0/apis/antivirus_api.py", line 30, in <module>
    from ..api_client import ApiClient
  File "/usr/lib/python2.6/site-packages/isi_sdk_8_0/api_client.py", line 145
    for k, v in iteritems(query_params)}
      ^
SyntaxError: invalid syntax
[root@nr-hdp-zoo2 isilon_data_insights_connector-master]#

**Comment by apecoraro** [comment]
The isi_sdk_7_2, isi_sdk_8_0, and isi_sdk_8_0_1 packages are not compatible with Python 2.6. I'm not sure if there is a way to specify the compatible versions of Python on pypi.python.org, but I'll send a note to the team that manages the SDK code on pypi to let them know.
