### ISSUE TITLE
Dashboard Import Issue (grafana 4.2.0)

### ISSUE THREAD

**Issue by sedwards2** [Isilon/isilon_data_insights_connector#28]
I was not able to directly import the dashboard files in Grafana 4.2.0 (I think the JSON schema must have changed a bit). I was able to give the dashboard url/number and that worked. Exporting those dashboards and re-importing them worked as well.

**Comment by apecoraro** [comment]
I just tested importing with Grafana 4.3.1 and it worked fine, so I'm guessing they did something to fix that problem.
