### ISSUE TITLE
data stops flowing into influxDB

### ISSUE THREAD

**Issue by Bigredraceing** [Isilon/isilon_data_insights_connector#34]
Hi I am not sure what is causing the issues I am having. I have 8 Isilon cluster and loose data points quite often and then it will stop collecting altogether. is there any recommendations on cpu storage and network setup to maybe help this be more stable?

I can collect any info you need to help with this issue.

Installed Packages
grafana.x86_64 4.3.2-1 @grafana
influxdb.x86_64 1.2.4-1 @influxdb
python.x86_64 2.7.5-48.el7 @anaconda
3.10.0-514.21.1.el7.x86_64
CentOS Linux release 7.3.1611 (Core)

**Comment by apecoraro** [comment]
Is your InfluxDB or Stats Connector dying due to inability to access enough of some hardware resource? I ask because your question about cpu, storage, and/or network setup seems to imply that lack of resources is creating instability. When data stops flowing into InfluxDB do you still see messages printed to the log file indicating that the Connector daemon is querying your Isilon cluster? Does InfluxDB still appear to be running? Can you connect to it via either its web interface or its command line interface?

**Comment by oddsrule** [comment]
Hi,
Yes, influxDB is still running, both as per systemctl and running processes.
Yes, can connect to the database via CLI and view the databases.
[root~]# influx
Connected to http://localhost:8086 version 1.2.4
InfluxDB shell version: 1.2.4
> show databases
name: databases
name
----
_internal
isi_data_insights

I'm not sure where the connector logs to however to verify if it is still logging.

**Comment by Bigredraceing** [comment]
oddsrule is working with me on this issue

**Comment by apecoraro** [comment]
The default settings are to have the Connector send log messages to ./isi_data_insights_d.log.

**Comment by oddsrule** [comment]
Thank you,
that log is updating, and ps does tell me that the connector daemon process is still running, even though the data shows missing periods of time quite regularly.

the log is flooded with entries like this:
Query for stat: 'node.ifs.heat.getattr.total' on 'isilon-cluster-1', returned error: 'Missing result, communication with remote resource timed
out'.

**Comment by apecoraro** [comment]
The node.* stats require the data to be internally gathered from all nodes on the cluster. The node that is doing the gathering will wait up to 60 seconds for the other nodes to reply.

What version is your cluster?

BTW, you can change the default settings for how long the gathering node will wait for remote nodes to reply to internal stat queries by modifying lines 34 and 92 of isi_stats_client.py. Change the "timeout=60" to "timeout=2" or anything smaller than 60. That will at least prevent it from waiting forever.

**Comment by Bigredraceing** [comment]
ok we have set the time out to 10 and we will see if that helps.

**Comment by oddsrule** [comment]
After changing both timeout=60 entries to timeout=10 we now see these error messages in the log.

"An unhandled exception occurred. Exception was: Timed out waiting for isi_stats_d connection lock after **10 secs**"

previously the same message was logged, but with a different timeout value

"An unhandled exception occurred. Exception was: Timed out waiting for isi_stats_d connection lock after **30 secs**"

**Comment by apecoraro** [comment]
It sounds like one or more of your nodes is in a bad and/or hung state. You will need to work with Dell EMC support to resolve the issue completely. To work around it, for the time being, you could try disabling the node.* stats in the Connector's config file. That will mean that only cluster wide stats will be queried and tracked by the Connector and hopefully you can avoid trying to query the stats from one of the nodes that seems to be hung up.

To disable node.* stats from being queried remove cluster_client_activity_stats, node_load_stats, node_disk_stats, node_net_stats, and heat_total_stats from the list of active stat groups as specified by the active_stat_groups parameter in the isi_data_insights_d.cfg config file.

**Comment by tenortim** [comment]
To @apecoraro's point, I suspect you may have a problem with the node BMC/CMC because this tends to affect the stats daemon on-cluster. Please work with support on this. There is updated firmware to address the issue.

**Comment by tenortim** [comment]
@Bigredraceing was there any resolution to this?

**Comment by tenortim** [comment]
Closing based on the above (looks like a cluster issue).
