### ISSUE TITLE
multi-point stats e.g. protostats are incomplete.

### ISSUE THREAD

**Issue by tenortim** [Isilon/isilon_data_insights_connector#38]
Example:
Run a benchmark NFS test that generates multiple RPC operations (create, read, write, commit, symlink etc.). Check the protocol stats detail page and most of the operations are missing in the breakout. Problem is handling of the list returned by the SDK, PR for fix to follow.

**Comment by apecoraro** [comment]
Fixed by this: fe95980bc5e11f597e18433baf2fc635ca2ef2bb
