### ISSUE TITLE
node-based stats queries only return first node again 7.2 clusters

### ISSUE THREAD

**Issue by tenortim** [Isilon/isilon_data_insights_connector#41]
The derived stats code somehow broke this.
Example: request stats for node.disk.iosched.latency.avg - an InfluxDB database entry is generated for every node in an 8.x cluster, but only against the first node for a 7.2 cluster.

PR with patch/fix to follow.

**Comment by apecoraro** [comment]
Fixed by ef1a8e9b63231d05ff229a34297da61f9521de92
