### ISSUE TITLE
Startup error on new install

### ISSUE THREAD

**Issue by rdeimling** [Isilon/isilon_data_insights_connector#46]
Hello, I am new to this connector and have just installed it. I have followed a guide (https://community.emc.com/blogs/keith/2017/01/26/isilon-data-insights-connector--do-it-yourself-isilon-monitoring) to do this install and got all the way down to where i have to start the isi_data_insights_d.py script. I am receiving the following error and do not know what to do from here. I am not a python programmer so go easy on me.

# ./isi_data_insights_d.py start
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 627, in configure_via_file
    args.stats_processor, args.processor_args)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 551, in _configure_stats_processor
    processor = __import__(stats_processor, fromlist=[''])
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/isilon_data_insights_connector/influxdb_plugin.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by apecoraro** [comment]
That's very weird. Did you happen to make any changes to the influxdb_plugin.py file? What does line 7 look like?

**Comment by rdeimling** [comment]
Looks like there were 6 spaced lines above it, so its actually line 1. here is the new error after removing the spaces, and after that is the first few lines of influxdb_plugin.py. I did not make any changes to that file.

Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 627, in configure_via_file
    args.stats_processor, args.processor_args)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 551, in _configure_stats_processor
    processor = __import__(stats_processor, fromlist=[''])
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/isilon_data_insights_connector/influxdb_plugin.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax


----------------------------------------------------------------

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  <link rel="dns-prefetch" href="https://assets-cdn.github.com">
  <link rel="dns-prefetch" href="https://avatars0.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars1.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars2.githubusercontent.com">
  <link rel="dns-prefetch" href="https://avatars3.githubusercontent.com">
  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">
  <link rel="dns-prefetch" href="https://user-images.githubusercontent.com/">



  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-bedfc518345498ab3204d330c1727cde7e733526a09cd7df6867f6a231565091.css" media="all" rel="stylesheet" />
  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/github-7fe2b92304082e7579ea9aaf717b05ebef9288ada19f3ff3afeca11b72e5f4aa.css" media="all" rel="stylesheet" />


  <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/site-877643c520258c4fa15ac8d1664d84efd0e3db56f5e544ccac58da0e50489904.css" media="all" rel="stylesheet" />


  <meta name="viewport" content="width=device-width">

  <title>isilon_data_insights_connector/influxdb_plugin.py at master · Isilon/isilon_data_insights_connector · GitHub</title>
  <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
  <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub">
  <meta property="fb:app_id" content="1401488693436528">

**Comment by apecoraro** [comment]
Can you attach your copy of influxdb_plugin.py to this thread? The fact that you say that there are 6 spaced lines at the start is a fishy sounding, the file is supposed to have several imports not empty lines, see here for the original copy: https://github.com/Isilon/isilon_data_insights_connector/blob/master/influxdb_plugin.py#L7

**Comment by rdeimling** [comment]
Put it in a .zip because it wont let me upload .py file types

I do see a influxdb_plugin.py.original on my system so i did make a backup of the original before doing anything else. 
[influxdb_plugin.zip](https://github.com/Isilon/isilon_data_insights_connector/files/1315415/influxdb_plugin.zip)

**Comment by apecoraro** [comment]
Yea, I'm not sure how you managed to do it, but that influxdb_plugin.py in the attached zip is not a python code file. It appears to be an html representation of the influxdb_plugin.py, if you change it's name to influxdb_plugin.html and open it in a browser then you can see what I'm talking about.

**Comment by apecoraro** [comment]
Assuming you got the code for the Connector by doing:
```
git clone https://github.com/Isilon/isilon_data_insights_connector.git
```
Then you should be able to reset it back to original state by running the following command from the /opt/isilon_data_insights_connector directory:

**Comment by rdeimling** [comment]
I run the command you have shown and now when i try and start i get this:

Unable to load stats processor: influxdb_plugin.

Maybe i should just delete the folder and try again.

**Comment by apecoraro** [comment]
Yea, I'm not sure what you did, but deleting the directory and trying the clone command again should (hopefully) fix it. You might want to save your isi_data_insights_d.cfg so you don't have to repeat that step.

**Comment by rdeimling** [comment]
Success. Sorry for the odd ball problem but i really appreciate your attempt to fix the issue. Hopefully I wont need to have any more help.

**Comment by argstarfire** [comment]
I have the same problem, if someone can help me, I appreciate it.

**Comment by fr3man1** [comment]
@argstarfire  Have you modified the influxdb_plugin.py file using windows and then transferred it to unix, just a guess tho. If so you could run dos2unix influxdb_plugin.py and see if helps.
