### ISSUE TITLE
Error using RBAC account for statistics gathering

### ISSUE THREAD

**Issue by nickyruggs** [Isilon/isilon_data_insights_connector#47]
I have an RBAC user called pmon that was setup to work on 8,0 cluster, this same user throws an error on startup for an Gen 6 8.1 cluster.  if i fall back to 'root' everyhting is fine.

h600-1# isi auth roles view perfmon
       Name: perfmon
Description: -
    Members: pmon
 Privileges
             ID: ISI_PRIV_LOGIN_PAPI
      Read Only: True

             ID: ISI_PRIV_STATISTICS
      Read Only: True
h600-1# 
h600-1# isi auth users view pmon                                                                
                    Name: pmon
                      DN: CN=pmon,CN=Users,DC=H600
              DNS Domain: -
                  Domain: H600
                Provider: lsa-local-provider:System
        Sam Account Name: pmon
                     UID: 2000
                     SID: S-1-5-21-3274664045-3880517804-3078641286-1000
                 Enabled: Yes
                 Expired: No
                  Expiry: -
                  Locked: No
                   Email: -
                   GECOS: -
           Generated GID: No
           Generated UID: No
           Generated UPN: Yes
           Primary Group
                          ID: GID:1800
                        Name: Isilon Users
          Home Directory: /ifs/home/pmon
        Max Password Age: 4W
        Password Expired: Yes
         Password Expiry: 2017-09-19T14:34:58
       Password Last Set: 2017-07-24T09:52:09
        Password Expires: Yes
                   Shell: /bin/zsh
                     UPN: pmon@H600
User Can Change Password: Yes

Here is the errors when i start....

[root@nr-hdp-c3 isilon_data_insights_connector-master]#  ./isi_data_insights_d.py start -c hadoop_isi_data_insights_d.cfg 
Failed to configure SDK for cluster 10.111.157.173. Exception raised: Failed to get cluster config for cluster https://10.111.157.173:8080 using SDK isi_sdk_7_2. Error: (401)
Reason: Authorization Required
HTTP response headers: HTTPHeaderDict({'Content-Length': '49', 'Accept-Ranges': 'bytes', 'Server': 'Apache/2.2.31 (FreeBSD) mod_ssl/2.2.31 OpenSSL/1.0.2j-fips mod_fastcgi/2.4.6', 'Last-Modified': 'Fri, 07 Apr 2017 21:35:07 GMT', 'ETag': '"15529-31-54c9a663558c0"', 'Date': 'Tue, 19 Sep 2017 14:30:15 GMT', 'Content-Type': 'application/json', 'WWW-Authenticate': 'Basic'})
HTTP response body: {"errors":[{"message":"authorization required"}]}

**Comment by dmtucker** [comment]
I'm pretty new to RBAC, but maybe this occurs due to an expired password?
```
Password Expired: Yes
```

**Comment by tenortim** [comment]
@nickyruggs did you get past this?
Can we close?

**Comment by nickyruggs** [comment]
yes

**Comment by tenortim** [comment]
Closing per response.
