### ISSUE TITLE
setup_venv.sh should use Python 2 for virtualenv

### ISSUE THREAD

**Issue by sedwards2** [Isilon/isilon_data_insights_connector#5]
Since the stats connector is not yet Python 3 compatible, the setup_venv.sh script should specify the Python 2 binary explicitly when creating a virtual environment.

**Comment by tenortim** [comment]
The connector is now functional with both Python 2 and 3 (thanks to the excellent [Future](https://python-future.org/) library), so I'm closing this as no longer needed.
