### ISSUE TITLE
Exception AttributeError: "'IsiApiClient_8_0' object has no attribute 'pool'

### ISSUE THREAD

**Issue by avafox** [Isilon/isilon_data_insights_connector#57]
Hi - Unable to successfully start the Isilon Data Insights Connector with the python script. 
# cat requirements.txt
daemons >= 1.3.0
influxdb >= 2.12.0
pip >= 8.0.2
urllib3 >= 1.13.1
isi_sdk_8_0 >= 0.1.2, < 0.2.0
isi_sdk_7_2 >= 0.1.2, < 0.2.0
Equation >= 1.2.01
gevent >= 1.2.1
root@udevbu1 #

root@udevbu1 #  ./isi_data_insights_d.py start
Please provide the username used to access *********.com via PAPI: root
Password:
Verify SSL cert [y/n]: n
Traceback (most recent call last):
  File "./isi_data_insights_d.py", line 65, in <module>
    main()
  File "./isi_data_insights_d.py", line 45, in main
    configure_via_file(daemon, args, config_file)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 668, in configure_via_file
    config_file, stat_group, global_cluster_list)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 298, in _configure_stat_groups_via_file
    cluster_configs = _build_cluster_configs(cluster_list)
  File "/opt/isilon_data_insights_connector/isi_data_insights_config.py", line 165, in _build_cluster_configs
    cluster, username, password, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_sdk_utils.py", line 56, in configure
    _detect_host_version(host_url, username, password, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_sdk_utils.py", line 87, in _detect_host_version
    api_client = api_client_class(host, verify_ssl)
  File "/opt/isilon_data_insights_connector/isi_api_client_8_0.py", line 20, in __init__
    super(IsiApiClient_8_0, self).__init__(host=host)
TypeError: __init__() got an unexpected keyword argument 'host'
Exception AttributeError: "'IsiApiClient_8_0' object has no attribute 'pool'" in <bound method IsiApiClient_8_0.__del__ of <isi_api_client_8_0.IsiApiClient_8_0 object at 0x7f190d501150>> ignored
root@udevbu1 # pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages (18.1)
root@udevbu1 # pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

**Comment by dmtucker** [comment]
This looks like #50. What SDK version do you have?

**Comment by avafox** [comment]
> 
> 
> This looks like #50. What SDK version do you have?

Ive checked and I do have deffo have the correct sdk 
pip install --no-binary :all: isi_sdk_8_0
Requirement already satisfied: _2in /usr/lib/python2.7/site-packages (0.2.5)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from isi_sdk_8_0) (1.11.0)
Requirement already satisfied: certifi in /usr/lib/python2.7/site-packages (from isi_sdk_8_0) (2018.10.15)
Requirement already satisfied: urllib3>=1.15 in /usr/lib/python2.7/site-packages (from isi_sdk_8_0) (1.24.1)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from isi_sdk_8_0) (2.7.5)
root@udevbu1 #
root@udevbu1 #  pip install --no-binary :all: isi_sdk_7_2
Collecting isi_sdk_7_2
  Downloading https://files.pythonhosted.org/packages/e1/9f/5cee6b6f7080c64e34a27978bdfba96b5fd99c622dc46339dcb547ce47ec/isi-sdk-7-2-0.2.5.tar.gz (568kB)
    100% |████████████████████████████████| 573kB 26.4MB/s
Requirement already satisfied: urllib3>=1.15 in /usr/lib/python2.7/site-packages (from isi_sdk_7_2) (1.24.1)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from isi_sdk_7_2) (1.11.0)
Requirement already satisfied: certifi in /usr/lib/python2.7/site-packages (from isi_sdk_7_2) (2018.10.15)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from isi_sdk_7_2) (2.7.5)
Installing collected packages: isi-sdk-7-2
  Running setup.py install for isi-sdk-7-2 ... done
Successfully installed isi-sdk-7-2-0.2.5

**Comment by dmtucker** [comment]
Looks like your SDKs are actually too new...
A version below 0.2.0 is currently required (you appear to have 0.2.5):
https://github.com/Isilon/isilon_data_insights_connector/blob/d7f452bf620208cfc8dcb7b9f5a99becc2c7bf09/requirements.txt#L5-L6

**Comment by avafox** [comment]
> pip install -r requirements.txt

Thanks - However it just defaults back to 0.2.5.. 
nstalling collected packages: isi-sdk-8-0, isi-sdk-7-2
Successfully installed isi-sdk-7-2-0.2.5 isi-sdk-8-0-0.2.5

root@udevbu1 # cat requirements.txt
daemons >= 1.3.0
influxdb >= 2.12.0
pip >= 8.0.2
urllib3 >= 1.13.1
isi_sdk_8_0 >= 0.2.0
isi_sdk_7_2 >= 0.2.0
Equation >= 1.2.01
gevent >= 1.2.1
root@udevbu1 #

**Comment by dmtucker** [comment]
That `requirements.txt` doesn't look correct.
We need *less than* 0.2.0 (which was a Major version change due to backwards-incompatible changes that the insights connector has not adapted to yet).

**Comment by avafox** [comment]
Ok will tinker around and let you know. Thanks for your help 


> 
> 
> That `requirements.txt` doesn't look correct.
> We need _less than_ 0.2.0 (which was a Major version change due to backwards-incompatible changes

**Comment by tenortim** [comment]
@avafox did you get past this?

**Comment by tenortim** [comment]
From the data collected above, the version of requirements.txt was old and missing the constraint to prevent pulling the newer SDK version. I'm about to fix the code to work correctly with the newer version, but I am closing this on the basis that we know what happened and that fixes are in place.
