### ISSUE TITLE
Isilon onefs 8.1.2 got error with metric node.cpu.throttling

### ISSUE THREAD

**Issue by ut0f9t** [Isilon/isilon_data_insights_connector#69]
Hello 
Not an issue just a question.
Im very surprise to got an error with the metric node.cpu.throttling with the version of isilon 8.1.2.
Could you confirm if it is normal or not?

**Comment by ut0f9t** [comment]
Hello for data_insights we are using the sdk 8.0.1.
2 clusters are in version v8.1.2.0 
13 clusters are in version v8.1.0.4

We Got an error on version 8.1.2.0 only 

ERROR:
xxxx-7# isi statistics query current list --keys=node.cpu.throttling 
An unhandled exception occurred. Exception was: system error for key 'node.cpu.throttling'

The support was asking if we are in compliance mode an not

Module                Licensed node count  Actual node count  Status     Expiration date
SMARTQUOTAS           8 Nodes              8 Nodes            Licensed   -
SNAPSHOTIQ            8 Nodes              8 Nodes            Licensed   -
SMARTCONNECT_ADVANCED 8 Nodes              8 Nodes            Licensed   -
SYNCIQ                8 Nodes              8 Nodes            Licensed   -
HDFS                  8 Nodes              8 Nodes            Licensed   -
SWIFT                 8 Nodes              8 Nodes            Licensed   -



---- output error  ---
2019-07-30 12:30:06,382:isi_data_insights_daemon:WARNING: Query for stat: 'node.cpu.throttling' on 'xxx', returned error: 'System resource unavailable'.
2019-07-30 12:30:06,382:isi_data_insights_daemon:WARNING: Query for stat: 'node.cpu.throttling' on 'xxx', returned error: 'System resource unavailable'.

**Comment by tenortim** [comment]
You are correct. "node.cpu.throttling" is no longer available in 8.1.2 or later. This needs to be removed from the config.
