### ISSUE TITLE
How to add new stats

### ISSUE THREAD

**Issue by Guiona** [Isilon/isilon_data_insights_connector#71]
Hello,

How I can add new stats to the collector please?
I want to retrieve quotas informations...

Regards,

**Comment by tenortim** [comment]
Hell @Guiona,
quotas aren't statistics. This project is mainly focused on performance-monitoring using the statistics interface. You can add new stats to the config file and create new graphs, but quotas aren't a performance statistic and need more thought. There is an open issue about quota support: #31

**Comment by tenortim** [comment]
Closing as I believe the question is answered and the quota enhancement request is covered in open issue #31.
