### ISSUE TITLE
startup woes with 8.2

### ISSUE THREAD

**Issue by nickyruggs** [Isilon/isilon_data_insights_connector#73]
found an issue starting up the data insights connector \\in the config file remove the 3 lines called node.mem.xxxx

they are no longer endpoints in the statistics api and you get a weird error which doesnt really explain it.. <below>
code" : "AEC_SERVICE_UNAVAILABLE",
"message" : "OneFS API is temporarily unavailable. Try your request again.

...just edit your config file and restart the connector daemon.

can someone update the example config files here.

**Comment by tenortim** [comment]
I believe this is a dup of #66?

**Comment by tenortim** [comment]
I believe the flurry for fixes I just merged solve resolve the issues with bad/missing stats in the config file. Closing. @nickyruggs please let me know if there are still problems and we can re-open or start a new issue.
