### ISSUE TITLE
unexpected keyword argument server_hostname

### ISSUE THREAD

**Issue by jjprachyl** [Isilon/isilon_data_insights_connector#74]
getting this error when attempting to start isi data insights py

using sdk 7.2 unexpected keyword argument ‘server_hostname’

How do i get past this?  i can’t get it to start

**Comment by tenortim** [comment]
Hi @jjprachyl, could you please list the details of how you are starting the collector and the full error message (I presume there's a stack trace?).

**Comment by jjprachyl** [comment]
Starting with the command “./isi_data_insights_d.py start”

it asks for credentials and validate cert (n)

then
“Failed to configure SDK for cluster x.x.x.x using sdk isi_sdk_7_2. Error: __init__() got an unexpected keyword argument ‘server_hostname’

**Comment by tenortim** [comment]
Hi @jjprachyl ,
I'm completely unable to reproduce the issue. "server_hostname" isn't in the source code for the data insights collector, nor is it in the SDK that I am aware of.
Could you provide details on how you are trying to set this up?
What OS/distro are you installing on?
Did you follow the instructions from README.md, and if so, which way did you try to set this up?
Would you be willing to upload a diff of your config file against the example config file provided (please obsfuscate any sensitive information such as passwords).

**Comment by jjprachyl** [comment]
Wow, don’t know what I did. I started over and ran into a lot of the issues in the issues section. Re-ran the requirements with sudo after upgrading setuptools. The instructions could be updated from Keith’s 2017 blog post. That would be helpful. I’m going to start over again and try to document my process to get an error free run through. Thanks for taking a look tenortim!

**Comment by tenortim** [comment]
Thanks @jjprachyl,
yes, updating the instructions is high on my list of updates that need to be made. I'm also looking into provide a dockerized version to simplify this.

**Comment by tenortim** [comment]
Closing this old issue. Please re-open or open a new one if there are problems.
