### ISSUE TITLE
easily swap back ends? 

### ISSUE THREAD

**Issue by jjprachyl** [Isilon/isilon_data_insights_connector#75]
Can I swap out influx for prometheus?

**Comment by tenortim** [comment]
Hi @jjprachyl,
the way the collector is coded, it is designed to allow pluggable back ends but the only supported back end in the current codebase is InfluxDB. To support Prometheus, a new back end plugin would need to be developed. I am definitely interested in Prometheus, but I haven't made time to investigate properly yet.

So the answer is that the collector is designed to allow pluggable back ends but somebody needs to write one for Prometheus.

**Comment by tenortim** [comment]
I just merged Prometheus support. Many thanks to @bernd-reize for doing the work!
